# Generated by Django 3.1 on 2020-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0002_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='circuit',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
